INTRODUCCIÓN A LA LIBRERÍA NUMPY

In [1]:
import numpy as np

def introduccion_arrays():
    """Introducción a NumPy - Importación y Creación de Arrays"""
    print("=" * 50)
    print("INTRODUCCIÓN A NUMPY - Importación y Creación de Arrays")
    print("=" * 50)

    # Crear el primer array (vector o arreglo) con NumPy
    arreglo_numerico = [1, 2, 3, 4, 5]
    vector_inicial = np.array(arreglo_numerico)

    print(f"El arreglo_numerico es del tipo = {type(arreglo_numerico)}")
    print(f"El vector_inicial es del tipo = {type(vector_inicial)}")
    print(f"Vector inicial: {vector_inicial}")

    # Crear una matriz
    matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(f"\nTipo de matriz: {type(matriz)}")
    print(f"Matriz:\n{matriz}")

    return vector_inicial, matriz

def operaciones_vectorizadas():
    """Operaciones Vectorizadas con NumPy"""
    print("=" * 50)
    print("OPERACIONES VECTORIZADAS")
    print("=" * 50)

    matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(f"Matriz original:\n{matriz}")

    # Multiplica todos los elementos por 2
    resultado = matriz * 2
    print(f"\nMatriz multiplicada por 2:\n{resultado}")

    # Otras operaciones vectorizadas
    suma_resultado = matriz + 10
    print(f"\nMatriz + 10:\n{suma_resultado}")

    potencia_resultado = matriz ** 2
    print(f"\nMatriz al cuadrado:\n{potencia_resultado}")

    return resultado

def crear_secuencias():
    """Crear Secuencias en Arreglos y Matrices"""
    print("=" * 50)
    print("CREAR SECUENCIAS EN ARREGLOS Y MATRICES")
    print("=" * 50)

    # Crear secuencia con arange
    arreglo_secuencial = np.arange(0, 10, 2)
    print(f"Secuencia con arange(0, 10, 2): {arreglo_secuencial}")

    # Crear secuencia con linspace
    arreglo_linspace = np.linspace(0, 1, 5)
    print(f"Secuencia con linspace(0, 1, 5): {arreglo_linspace}")

    # Crear secuencia con logspace
    arreglo_logspace = np.logspace(0, 2, 5)
    print(f"Secuencia con logspace(0, 2, 5): {arreglo_logspace}")

    return arreglo_secuencial, arreglo_linspace, arreglo_logspace

def matrices_especiales():
    """Creación de Matrices Especiales - Ceros, Unos, Aleatorias"""
    print("=" * 50)
    print("CREACIÓN DE MATRICES ESPECIALES")
    print("=" * 50)
    print("Utilidad: procedimientos de prueba, inicialización de redes neuronales,")
    print("generación de datos ficticios")
    print()

    # Matriz de ceros
    matriz_ceros = np.zeros((3, 3))
    print(f"Matriz de ceros (3x3):\n{matriz_ceros}")

    # Matriz de unos
    matriz_unos = np.ones((3, 3))
    print(f"\nMatriz de unos (3x3):\n{matriz_unos}")

    # Matriz identidad
    matriz_identidad = np.eye(3)
    print(f"\nMatriz identidad (3x3):\n{matriz_identidad}")

    # Matriz aleatoria
    np.random.seed(42)  # Para reproducibilidad
    matriz_aleatoria = np.random.rand(3, 3)
    print(f"\nMatriz aleatoria (3x3):\n{matriz_aleatoria}")

    # Matriz con valores específicos
    matriz_llena = np.full((3, 3), 7)
    print(f"\nMatriz llena de 7s (3x3):\n{matriz_llena}")

    return matriz_ceros, matriz_unos, matriz_identidad, matriz_aleatoria, matriz_llena

def seleccion_elementos():
    """Selección de Elementos en Arrays y Matrices"""
    print("=" * 50)
    print("SELECCIÓN DE ELEMENTOS")
    print("=" * 50)

    # Selección en vector
    vector = np.array([1, 2, 3, 4, 5])
    elemento_seleccion = vector[2]
    print(f"Vector: {vector}")
    print(f"Elemento en índice 2: {elemento_seleccion}")

    # Selección en matriz
    matriz_seleccion = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    elemento_seleccion_matriz = matriz_seleccion[1, 1]
    print(f"\nMatriz:\n{matriz_seleccion}")
    print(f"Elemento en posición [1,1]: {elemento_seleccion_matriz}")

    # Selección múltiple
    indices = [0, 2, 4]
    elementos_multiples = vector[indices]
    print(f"\nElementos en índices {indices}: {elementos_multiples}")

    # Selección condicional
    elementos_mayores = vector[vector > 3]
    print(f"Elementos mayores a 3: {elementos_mayores}")

    return vector, matriz_seleccion, elemento_seleccion_matriz

def submatrices_slicing():
    """Submatrices por Slicing"""
    print("=" * 50)
    print("SUBMATRICES POR SLICING")
    print("=" * 50)

    matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(f"Matriz original:\n{matriz}")

    # Extraer submatriz (filas 0-1, columnas 1-2)
    submatriz = matriz[0:2, 1:3]
    print(f"\nSubmatriz [0:2, 1:3]:\n{submatriz}")

    # Extraer toda una columna
    columna = matriz[:, 0]
    print(f"\nPrimera columna completa: {columna}")

    # Extraer toda una fila
    fila = matriz[1, :]
    print(f"Segunda fila completa: {fila}")

    # Extraer elementos alternos
    elementos_alternos = matriz[::2, ::2]
    print(f"\nElementos alternos:\n{elementos_alternos}")

    return matriz, submatriz, columna, fila

def funciones_estadisticas():
    """Funciones Estadísticas con NumPy"""
    print("=" * 50)
    print("FUNCIONES ESTADÍSTICAS CON NUMPY")
    print("=" * 50)

    datos = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    print(f"Datos: {datos}")
    print()

    # Calcular estadísticas
    media = np.mean(datos)
    mediana = np.median(datos)
    desviacion = np.std(datos)
    varianza = np.var(datos)
    minimo = np.min(datos)
    maximo = np.max(datos)
    suma = np.sum(datos)

    # Mostrar resultados organizados
    estadisticas = {
        'Media': media,
        'Mediana': mediana,
        'Desviación Estándar': desviacion,
        'Varianza': varianza,
        'Valor Mínimo': minimo,
        'Valor Máximo': maximo,
        'Sumatoria': suma
    }

    print("RESULTADOS ESTADÍSTICOS:")
    print("-" * 30)
    for nombre, valor in estadisticas.items():
        print(f"{nombre:20}: {valor:.4f}")

    # Estadísticas adicionales
    percentil_25 = np.percentile(datos, 25)
    percentil_75 = np.percentile(datos, 75)
    rango = maximo - minimo

    print(f"\nESTADÍSTICAS ADICIONALES:")
    print("-" * 30)
    print(f"{'Percentil 25':20}: {percentil_25:.4f}")
    print(f"{'Percentil 75':20}: {percentil_75:.4f}")
    print(f"{'Rango':20}: {rango:.4f}")

    return datos, estadisticas

def operaciones_matriciales():
    """Operaciones Matriciales Avanzadas"""
    print("=" * 50)
    print("OPERACIONES MATRICIALES AVANZADAS")
    print("=" * 50)

    # Crear matrices de ejemplo
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

    print(f"Matriz A:\n{A}")
    print(f"\nMatriz B:\n{B}")

    # Multiplicación de matrices
    producto_matricial = np.dot(A, B)
    print(f"\nProducto matricial (A @ B):\n{producto_matricial}")

    # Transposición
    A_transpuesta = A.T
    print(f"\nTranspuesta de A:\n{A_transpuesta}")

    # Determinante
    det_A = np.linalg.det(A)
    print(f"\nDeterminante de A: {det_A:.4f}")

    # Inversa
    try:
        inv_A = np.linalg.inv(A)
        print(f"\nInversa de A:\n{inv_A}")
    except np.linalg.LinAlgError:
        print("\nLa matriz A no es invertible")

    # Valores y vectores propios
    eigenvalues, eigenvectors = np.linalg.eig(A)
    print(f"\nValores propios de A: {eigenvalues}")
    print(f"Vectores propios de A:\n{eigenvectors}")

    return A, B, producto_matricial, A_transpuesta

def menu_principal():
    """Función principal que muestra el menú de opciones"""
    opciones = {
        '1': ('Introducción a Arrays', introduccion_arrays),
        '2': ('Operaciones Vectorizadas', operaciones_vectorizadas),
        '3': ('Crear Secuencias', crear_secuencias),
        '4': ('Matrices Especiales', matrices_especiales),
        '5': ('Selección de Elementos', seleccion_elementos),
        '6': ('Submatrices por Slicing', submatrices_slicing),
        '7': ('Funciones Estadísticas', funciones_estadisticas),
        '8': ('Operaciones Matriciales Avanzadas', operaciones_matriciales),
        '0': ('Salir', None)
    }

    while True:
        print("\n" + "=" * 60)
        print("         TUTORIAL INTERACTIVO DE NUMPY")
        print("=" * 60)
        print("Seleccione una característica de NumPy para explorar:")
        print("-" * 60)

        for codigo, (descripcion, _) in opciones.items():
            print(f"  {codigo}. {descripcion}")

        print("-" * 60)
        opcion = input("\nIngrese su opción: ").strip()

        if opcion == '0':
            print("\n¡Gracias por usar el tutorial de NumPy!")
            print("¡Hasta la vista, baby! 🤖")
            break
        elif opcion in opciones and opcion != '0':
            print("\n")
            try:
                opciones[opcion][1]()
                input("\nPresione Enter para continuar...")
            except Exception as e:
                print(f"Error al ejecutar la función: {e}")
        else:
            print("\n❌ Opción no válida. Por favor, seleccione una opción del menú.")

# Ejecutar el menú principal
menu_principal()


         TUTORIAL INTERACTIVO DE NUMPY
Seleccione una característica de NumPy para explorar:
------------------------------------------------------------
  1. Introducción a Arrays
  2. Operaciones Vectorizadas
  3. Crear Secuencias
  4. Matrices Especiales
  5. Selección de Elementos
  6. Submatrices por Slicing
  7. Funciones Estadísticas
  8. Operaciones Matriciales Avanzadas
  0. Salir
------------------------------------------------------------


INTRODUCCIÓN A NUMPY - Importación y Creación de Arrays
El arreglo_numerico es del tipo = <class 'list'>
El vector_inicial es del tipo = <class 'numpy.ndarray'>
Vector inicial: [1 2 3 4 5]

Tipo de matriz: <class 'numpy.ndarray'>
Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

         TUTORIAL INTERACTIVO DE NUMPY
Seleccione una característica de NumPy para explorar:
------------------------------------------------------------
  1. Introducción a Arrays
  2. Operaciones Vectorizadas
  3. Crear Secuencias
  4. Matrices Especiales
  5. Selección de 

KeyboardInterrupt: Interrupted by user